name: MacOS
on:
    push:
        branches-ignore:
            - "releases/**"
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "windows.yml"
            - "ubuntu.yml"
    pull_request:
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "windows.yml"
            - "ubuntu.yml"
jobs:
    test:
        name: Build
        runs-on: macos-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v2
            - name: Build
              run: |
                  cmake -B build -DSTOPWATCH_BUILD_EXAMPLES=ON -DSTOPWATCH_WARNINGS_AS_ERRORS=ON
                  cmake --build build --parallel 2