name: Ubuntu

# Trigger the workflow on push or pull requests for main and develop branches
on:
  push:
    branches:
    - main
    - develop
    paths:
    - '**/*.c'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/CMakeLists.txt'
    - '**/Makefile'
    - '**/cmake/**'
    - '.github/workflows/ubuntu.yml'
  pull_request:
    branches:
    - main
    - develop
    paths:
    - '**/*.c'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/CMakeLists.txt'
    - '**/Makefile'
    - '**/cmake/**'
    - '.github/workflows/ubuntu.yml'

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}

    # Define a matrix strategy to test multiple compiler and OS configurations
    strategy:
      # Continue running other matrix jobs even if one fails
      fail-fast: false
      matrix:
        include:
          [
            # GCC 8: Introduced full C++17 support.
            { pkgs: "gcc-8 g++-8", cc: gcc-8, cxx: g++-8, os: ubuntu-20.04 },
            # GCC 10: Improved performance and C++20 support.
            { pkgs: "gcc-10 g++-10", cc: gcc-10, cxx: g++-10, os: ubuntu-22.04 },
            # GCC 12: Latest stable version with full C++20 support.
            { pkgs: "gcc-12 g++-12", cc: gcc-12, cxx: g++-12, os: ubuntu-24.04 },

            # Clang 9: Full C++17 support.
            { pkgs: "clang-9 clang++-9", cc: clang-9, cxx: clang++-9, os: ubuntu-20.04 },
            # Clang 12: C++20 support improvements.
            { pkgs: "clang-12 clang++-12", cc: clang-12, cxx: clang++-12, os: ubuntu-22.04 },
            # Clang 14: Latest stable version with full C++20 support.
            { pkgs: "clang-14 clang++-14", cc: clang-14, cxx: clang++-14, os: ubuntu-24.04 } 
          ]

    # Set environment variables for compiler executables
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
    # Step: Clone the project.
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step: Install the required compiler and dependencies.
    - name: Install Compiler Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.pkgs }}

    # Step: Configure the project using CMake.
    - name: Configure Project
      run: |
        cmake -B build -DCMAKE_C_COMPILER=${{ env.CC }} -DCMAKE_CXX_COMPILER=${{ env.CXX }} -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON -DWARNINGS_AS_ERRORS=ON -DSTRICT_WARNINGS=ON

    # Step: Build Project.
    - name: Build Project
      run: |
        cmake --build build --config Debug --parallel 2

    # Step: Run Tests.
    - name: Run Tests
      run: |
        ctest --test-dir build --build-config Debug --verbose
